fixed bug - main btn
DmitriyDemyanov/travel-agency pull request #4
Opened 2023-06-10 13:10 UTC by DmitriyDemyanov

2023-06-10 18:19 UTC, khlepitko-gennady requested changes

2023-06-10 18:19 UTC, khlepitko-gennady commented on src/components/MainButtonComponent.vue
> +  <button class="main-button" :class='[`size-${size}`,`color-${color}`,`type-${type}`]' @click='$emit("mainBtn")'>
Плохое название для события. Оно должно описывать что произошло. Давай использовать button-click, btn-click можно вообще просто $emit("click") и слушать соответственно событие @click=... в родителе.

2023-06-10 18:19 UTC, khlepitko-gennady commented on src/components/HeaderComponent.vue
>          </div>
clickBtn - это слишком абстрактно.
Давай сделаем две функции, которые будут реагировать в зависимости от того, какая кнопка нажата. Если нажали на Login - вызов функции userLogin. Если нажали на Sign Up - вызов функции userSignUp

2023-06-14 17:46 UTC, DmitriyDemyanov commented on src/components/HeaderComponent.vue
>          </div>
Done

2023-06-14 17:54 UTC, merged